# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "cd /vagrant" >> /home/vagrant/.bashrc
echo ":set number" >> /home/vagrant/.vimrc
echo ":set nowrap" >> /home/vagrant/.vimrc
echo ":colorscheme industry" >> /home/vagrant/.vimrc
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define "2-single-node" do |s1|
      s1.vm.box = "ubuntu/xenial64"
      s1.vm.network :private_network, ip: "10.0.0.10", virtualbox__intnet: "network2"
      s1.vm.hostname = "2-single-node"
      s1.vm.provision "shell", inline: $script
  end
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
end
