# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "cd /vagrant" >> /home/vagrant/.bashrc
echo ":set number" >> /home/vagrant/.vimrc
echo ":set nowrap" >> /home/vagrant/.vimrc
echo ":colorscheme industry" >> /home/vagrant/.vimrc
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define "3-multi-node-1" do |s1|
      s1.vm.box = "ubuntu/xenial64"
      s1.vm.network :private_network, ip: "10.0.0.10", virtualbox__intnet: "network3"
      s1.vm.hostname = "3-multi-node-1"
      s1.vm.provision "shell", inline: $script
  end
  config.vm.define "3-multi-node-2" do |s2|
      s2.vm.box = "ubuntu/xenial64"
      s2.vm.network :private_network, ip: "10.0.0.20", virtualbox__intnet: "network3"
      s2.vm.hostname = "3-multi-node-2"
      s2.vm.provision "shell", inline: $script
  end
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
end
