# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
apt-get update
apt-get install socat
echo "cd /vagrant" >> /home/vagrant/.bashrc
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define "container-networking-1" do |s1|
      s1.vm.box = "ubuntu/xenial64"
      s1.vm.network :private_network, ip: "10.0.0.10"
      s1.vm.hostname = "container-networking-1"
      s1.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      end
      s1.vm.provision "shell", inline: $script
  end
  config.vm.define "container-networking-2" do |s2|
      s2.vm.box = "ubuntu/xenial64"
      s2.vm.network :private_network, ip: "10.0.0.20"
      s2.vm.hostname = "container-networking-2"
      s2.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      end
      s2.vm.provision "shell", inline: $script
  end
end
