# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo "cd /vagrant" >> /home/vagrant/.bashrc
echo "ln -sf /vagrant/.vim /home/vagrant/.vim" >> /home/vagrant/.bashrc
echo "ln -sf /vagrant/.vimrc /home/vagrant/.vimrc" >> /home/vagrant/.bashrc
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define "1-network-namespace" do |s1|
      s1.vm.box = "ubuntu/xenial64"
      s1.vm.network :private_network, ip: "10.0.0.10", virtualbox__intnet: "network1"
      s1.vm.hostname = "1-network-namespace"
      s1.vm.provision "shell", inline: $script
  end
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
end
