# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "container-networking" do |s1|
      s1.vm.box = "ubuntu/xenial64"
      s1.vm.network :private_network, ip: "10.0.0.10"
      s1.vm.hostname = "container-networking"
      s1.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      end
  end
end
